name: Update

on: push
#  - schedule:
#    - cron: "0 0 * * *"

jobs:
  update_job:
    runs-on: ubuntu-latest
    steps:
    - name: Update packages
      uses: kallsyms/apple-opensource@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
